# Generated by Django 3.1.dev20200307214613 on 2020-04-12 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phoneNumber', models.IntegerField()),
                ('numberOfPurchase', models.IntegerField()),
                ('sale', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
                ('feedbackDate', models.DateTimeField()),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbackId', to='web_console.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('orderedDate', models.DateField()),
                ('shippedDate', models.DateField()),
                ('status', models.BooleanField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderId', to='web_console.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLines',
            fields=[
                ('productLine', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productCode', models.IntegerField(primary_key=True, serialize=False)),
                ('productName', models.TextField()),
                ('instock', models.IntegerField()),
                ('sold', models.IntegerField()),
                ('sale', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Line', to='web_console.ProductLines')),
            ],
        ),
        migrations.DeleteModel(
            name='Pos',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Code', to='web_console.Products'),
        ),
    ]
