# Generated by Django 3.1.dev20200307214613 on 2020-04-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '002_auto_20200416_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart',
            new_name='product',
        ),
    ]
