# Generated by Django 3.1.dev20200307214613 on 2020-04-12 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0002_auto_20200413_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartCode', to='web_console.Products'),
        ),
    ]
