# Generated by Django 3.1.dev20200307214613 on 2020-04-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0003_auto_20200419_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product',
            new_name='productLine',
        ),
    ]
