# Generated by Django 3.1.dev20200307214613 on 2020-04-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0004_auto_20200419_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(max_length=50),
        ),
    ]
