# Generated by Django 3.1.dev20200307214613 on 2020-04-12 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0004_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_console.Order'),
        ),
    ]
