# Generated by Django 3.1.dev20200307214613 on 2020-04-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0005_auto_20200413_0154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pos',
        ),
    ]
