# Generated by Django 3.1.dev20200307214613 on 2020-04-19 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0005_auto_20200419_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='customer',
        ),
    ]
