# Generated by Django 3.1.dev20200307214613 on 2020-04-19 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0006_auto_20200419_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackId', to='web_console.Customer'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackCode', to='web_console.Products'),
        ),
    ]
