# Generated by Django 3.1.dev20200307214613 on 2020-04-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0007_auto_20200419_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image1',
            field=models.ImageField(default=None, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(default=None, upload_to='pictures/'),
        ),
    ]
