# Generated by Django 3.1.dev20200307214613 on 2020-04-12 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0007_auto_20200413_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orders',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orderCode', to='web_console.Cart'),
        ),
    ]
