# Generated by Django 3.1.dev20200307214613 on 2020-04-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0008_order_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
