# Generated by Django 3.1.dev20200307214613 on 2020-04-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0008_auto_20200420_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback',
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(default='New', max_length=30),
        ),
    ]
