# Generated by Django 3.1.dev20200307214613 on 2020-04-22 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0009_auto_20200422_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orders',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
