# Generated by Django 3.1.dev20200307214613 on 2020-04-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0009_auto_20200413_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='abc',
            field=models.TextField(default=''),
        ),
    ]
