# Generated by Django 3.1.dev20200307214613 on 2020-04-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0011_auto_20200413_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default=None, upload_to='pictures/'),
        ),
    ]
