# Generated by Django 3.1.dev20200307214613 on 2020-04-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0011_auto_20200422_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='numberOfPurchase',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sale',
            field=models.IntegerField(default=0),
        ),
    ]
