# Generated by Django 3.1.dev20200307214613 on 2020-04-13 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0012_auto_20200413_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cartCode', serialize=False, to='web_console.Products', unique=True),
        ),
    ]
