# Generated by Django 3.1.dev20200307214613 on 2020-04-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0012_auto_20200422_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='userID',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='web_console.Customer'),
        ),
    ]
