# Generated by Django 3.1.dev20200307214613 on 2020-04-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0013_auto_20200413_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='images',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='products',
            name='productName',
            field=models.CharField(max_length=50),
        ),
    ]
