# Generated by Django 3.1.dev20200307214613 on 2020-04-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0014_auto_20200422_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='username',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
