# Generated by Django 3.1.dev20200307214613 on 2020-04-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0015_auto_20200414_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default=None, upload_to='pictures/'),
        ),
    ]
