# Generated by Django 3.1.dev20200307214613 on 2020-04-23 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0016_auto_20200424_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(db_column='customer', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='web_console.Customer'),
        ),
    ]
