# Generated by Django 3.1.dev20200307214613 on 2020-04-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0018_auto_20200425_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
