# Generated by Django 3.1.dev20200307214613 on 2020-04-25 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0019_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='sale',
        ),
    ]
