# Generated by Django 3.1.dev20200307214613 on 2020-04-16 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phoneNumber', models.IntegerField()),
                ('numberOfPurchase', models.IntegerField()),
                ('sale', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
                ('feedbackDate', models.DateTimeField()),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbackId', to='web_console.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('orderedDate', models.DateField()),
                ('shippedDate', models.DateField()),
                ('status', models.BooleanField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderId', to='web_console.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLines',
            fields=[
                ('productLine', models.CharField(max_length=50,primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productCode', models.IntegerField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=50)),
                ('instock', models.IntegerField()),
                ('sold', models.IntegerField()),
                ('sale', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(default=None, upload_to='pictures/')),
                ('images', models.CharField(default='', max_length=150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Line', to='web_console.ProductLines')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cartCode', serialize=False, to='web_console.Products', unique=True)),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pos',
        ),
        migrations.AddField(
            model_name='order',
            name='orders',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orderCode', to='web_console.Cart'),
        ),
    ]
